[package]
name = "compact-bar-plus"
version = "0.1.0"
authors = ["Alexander Kenji Berthold <aks.kenji@protonmail.com>" ]
edition = "2021"
license = "MIT"

[dependencies]
colored = "2"
ansi_term = "0.12"
chrono = { version = "0.4.39", default-features = false, features = ["clock"] }
unicode-width = "0.1.8"
zellij-tile = "0.44.3"
zellij-tile-utils = "0.44.3"
